create table year (job_id int primary key,
 company_id integer,    
 job_title_short varchar(255),    
 job_titl text,         
 job_location text,         
 job_via text,         
 job_schedule_type text,         
 job_work_from_home boolean,         
 search_location text,         
 job_posted_date timestamp,
 job_no_degree_mention boolean ,         
 job_health_insurance boolean);